"""Black-box behaviour tests for iter 09 -- the `render_agents_md` helper +
the on-demand `foundry agents` CLI subcommand (emit an AGENTS.md house-rules
file into a product repo from its learnings).

ISOLATION: written from the PM spec (Expected Behaviors 1-12) and the product's
own observable behavior only. The implementation source (foundry.py internals),
the engineer/reviewer notes, and `git diff` were NOT read. Every check drives
the public interface: the pure helper `foundry.render_agents_md(text, name,
recent=...)` against synthetic input strings, and the CLI via
`foundry.main(["agents", ...])` with a temp config whose `repo` field is a tmp
dir (the real foundry repo is NEVER touched). Expected content is computed via
the public pure helpers `foundry.render_agents_md(...)` / `foundry.learnings_digest(...)`.
Fully offline and deterministic -- real temp files only, NO subprocess/git/network/
agent-run except the `--help` regression probe (which only prints usage and exits).
"""
import json
import pathlib
import sys

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
import foundry  # noqa: E402
import dispatcher  # noqa: E402


# --------------------------------------------------------------------------
# helpers (mirror the suite's conventions; repo defaults to a TMP dir so the
# `agents` command can never write into the real foundry repo -- Behavior 11)
# --------------------------------------------------------------------------
def _write_cfg(tmp_path, **over):
    data = {
        "name": "demoprod",
        "repo": str(tmp_path / "repo"),          # TMP repo -> real repo untouched
        "allowed_push_repo": "demoprod",
        "vision": str(tmp_path / "VISION.md"),
        "work_root": str(tmp_path / "work"),
    }
    data.update(over)
    p = tmp_path / "config.json"
    p.write_text(json.dumps(data))
    return p


def _cfg_with_learnings(tmp_path, file_text, **over):
    """Load a config + seed <work_root>/LEARNINGS.md (cfg.learnings) with text."""
    cfg = foundry.load_config(str(_write_cfg(tmp_path, **over)))
    lp = pathlib.Path(cfg.learnings)
    lp.parent.mkdir(parents=True, exist_ok=True)
    lp.write_text(file_text)
    return cfg


def _marker(i):
    return f"UNIQMARK-{i:03d}"


def _lesson(i, tag="ENG"):
    """A role-tagged lesson line: `- [ENG iterNN] <unique marker> ...`."""
    return f"- [{tag} iter{i:02d}] {_marker(i)} some durable detail text here"


def _patterns_head(*bullets):
    """A `## Patterns` head: heading + blurb + plain `- ` pattern bullets."""
    lines = ["## Patterns", "", "Read this head first; the tail is the history.", ""]
    lines += [f"- {b}" for b in bullets]
    return "\n".join(lines)


def _learnings_text(n_lessons, *patterns):
    """A realistic LEARNINGS.md: patterns head + chronological lessons tail."""
    head = _patterns_head(*patterns) if patterns else _patterns_head("a durable rule")
    tail = "\n".join(_lesson(i) for i in range(1, n_lessons + 1))
    return head + "\n\n## Chronological lessons\n\n" + tail + "\n"


def _count_lesson_lines(text):
    """Count lines whose left-stripped form starts with the 3 chars '- ['."""
    return sum(1 for ln in text.splitlines() if ln.lstrip().startswith("- ["))


def _first_nonempty_line(text):
    for ln in text.splitlines():
        if ln.strip():
            return ln
    return ""


# ==========================================================================
# A. Pure helper render_agents_md(learnings_text, product_name, recent=12)
# ==========================================================================

# --- Behavior 1 -- non-empty, deterministic (pure), never raises -----------
def test_b01_nonempty_deterministic_pure():
    for text in ("", _learnings_text(4, "p1", "p2")):
        a = foundry.render_agents_md(text, "ProdName-Alpha")   # must not raise
        b = foundry.render_agents_md(text, "ProdName-Alpha")   # identical args
        assert isinstance(a, str) and a != "", "render_agents_md returned empty/non-str"
        assert a == b, "render_agents_md is not deterministic for identical args"
        # byte-identical, per the spec's purity requirement
        assert a.encode("utf-8") == b.encode("utf-8")


# --- Behavior 2 -- top heading names the product ---------------------------
def test_b02_top_heading_names_product():
    name = "MyCoolProduct-XYZ"
    out = foundry.render_agents_md(_learnings_text(3), name)
    first = _first_nonempty_line(out)
    assert first.startswith("# "), f"first non-empty line is not a top-level `# ` heading: {first!r}"
    assert name in first, f"product name {name!r} not present verbatim in the top heading: {first!r}"


# --- Behavior 3 -- auto-generated banner with the 3 literal substrings ------
def test_b03_autogenerated_banner_substrings():
    # learnings text I control contains NONE of the banner literals, so the
    # "banner sits above the learnings content" ordering check is meaningful.
    text = _learnings_text(3, "just a plain rule")
    out = foundry.render_agents_md(text, "BannerProd")
    for lit in ("auto-generated", "foundry agents", "LEARNINGS.md"):
        assert lit in out, f"banner literal {lit!r} missing from render output"
    # banner is ABOVE the embedded learnings content (digest)
    digest = foundry.learnings_digest(text, recent=12)
    assert out.find("auto-generated") < out.find(digest), "banner does not precede the learnings digest"


# --- Behavior 4 -- embeds the bounded learnings digest VERBATIM -------------
def test_b04_embeds_digest_verbatim():
    text = _learnings_text(6, "pattern alpha", "pattern beta")
    for recent in (4, 12):
        out = foundry.render_agents_md(text, "EmbedProd", recent=recent)
        expected = foundry.learnings_digest(text, recent=recent)
        assert expected in out, (
            f"learnings_digest(text, recent={recent}) is not a contiguous substring "
            "of render_agents_md output (digest not embedded verbatim)"
        )


# --- Behavior 5 -- `recent` bounds the embedded lessons + accurate header ---
def test_b05_recent_bounds_lessons_and_header():
    M = 5
    text = _learnings_text(M, "a rule")   # ids 1..5
    for recent in (0, 3, 5, 12):
        out = foundry.render_agents_md(text, "BoundProd", recent=recent)
        k = min(recent, M)
        # count of `- [` lesson lines in the WHOLE returned string == min(recent, M)
        assert _count_lesson_lines(out) == k, (
            f"recent={recent}: expected {k} lesson lines, got {_count_lesson_lines(out)}"
        )
        # header reports K == min(recent, M) and the true M
        assert f"## Recent lessons (last {k} of {M})" in out, (
            f"recent={recent}: header '## Recent lessons (last {k} of {M})' not found"
        )
    # recent == 0 -> exactly zero, no negative-slice wrap-around
    out0 = foundry.render_agents_md(text, "BoundProd", recent=0)
    assert _count_lesson_lines(out0) == 0
    for i in range(1, M + 1):
        assert _marker(i) not in out0, "recent=0 leaked a lesson (negative-slice wrap-around?)"


# --- Behavior 6 -- empty learnings -> stable placeholder --------------------
def test_b06_empty_learnings_stable_placeholder():
    out = foundry.render_agents_md("", "EmptyProd")
    # still satisfies Behaviors 1-3
    assert isinstance(out, str) and out != ""
    first = _first_nonempty_line(out)
    assert first.startswith("# ") and "EmptyProd" in first
    for lit in ("auto-generated", "foundry agents", "LEARNINGS.md"):
        assert lit in out
    # embeds the placeholder digest (== learnings_digest("", recent=12))
    placeholder = foundry.learnings_digest("", recent=12)
    assert placeholder in out, "empty-text placeholder digest not embedded"
    assert "## Recent lessons (last 0 of 0)" in out
    assert _count_lesson_lines(out) == 0


# ==========================================================================
# B. CLI subcommand `foundry agents --config <cfg> [--recent N] [--print]`
# ==========================================================================

# --- Behavior 7 -- default WRITES the repo's AGENTS.md ---------------------
def test_b07_default_writes_repo_agents_md(tmp_path, capsys):
    text = _learnings_text(6, "cli pat one", "cli pat two")
    cfg = _cfg_with_learnings(tmp_path, text)
    cfg_path = tmp_path / "config.json"
    agents_md = pathlib.Path(cfg.repo) / "AGENTS.md"
    assert not agents_md.exists(), "precondition: AGENTS.md must not exist yet"

    rc = foundry.main(["agents", "--config", str(cfg_path)])
    capsys.readouterr()
    assert rc == 0, f"agents returned {rc!r}, expected 0"
    assert agents_md.exists(), "default agents did not write <cfg.repo>/AGENTS.md"
    # exact contents == render_agents_md(<learnings-text>, cfg.name, recent=12)
    expected = foundry.render_agents_md(text, cfg.name, recent=12)
    assert agents_md.read_text() == expected, "written AGENTS.md != render_agents_md(text, name, 12)"


# --- Behavior 8 -- `--print` prints and writes NOTHING ---------------------
def test_b08_print_prints_writes_nothing(tmp_path, capsys):
    text = _learnings_text(5, "print pat")
    cfg = _cfg_with_learnings(tmp_path, text)
    cfg_path = tmp_path / "config.json"
    agents_md = pathlib.Path(cfg.repo) / "AGENTS.md"
    assert not agents_md.exists(), "precondition: AGENTS.md must not exist yet"

    rc = foundry.main(["agents", "--config", str(cfg_path), "--print"])
    out = capsys.readouterr().out
    assert rc == 0, f"agents --print returned {rc!r}, expected 0"
    expected = foundry.render_agents_md(text, cfg.name, recent=12)
    assert expected in out, "--print did not write the rendered document to stdout"
    # writes NOTHING: the file that did not exist before still does not exist
    assert not agents_md.exists(), "--print created/modified <cfg.repo>/AGENTS.md (must not)"


# --- Behavior 9 -- `--recent N` bounds the output (default 12) --------------
def test_b09_recent_bounds_cli_output(tmp_path, capsys):
    text = _learnings_text(6, "pat")   # M = 6 lessons -> 3 != 12-bounded
    cfg = _cfg_with_learnings(tmp_path, text)
    cfg_path = tmp_path / "config.json"
    agents_md = pathlib.Path(cfg.repo) / "AGENTS.md"

    # --recent 3 -> content == render(..., recent=3), at most 3 `- [` lines
    rc = foundry.main(["agents", "--config", str(cfg_path), "--recent", "3"])
    capsys.readouterr()
    assert rc == 0
    written = agents_md.read_text()
    assert written == foundry.render_agents_md(text, cfg.name, recent=3)
    assert _count_lesson_lines(written) == 3, "at most 3 lesson lines expected with --recent 3"

    # default (no --recent) -> recent == 12 (keeps all 6, differs from recent=3)
    rc = foundry.main(["agents", "--config", str(cfg_path)])
    capsys.readouterr()
    assert rc == 0
    written_default = agents_md.read_text()
    assert written_default == foundry.render_agents_md(text, cfg.name, recent=12)
    assert written_default != foundry.render_agents_md(text, cfg.name, recent=3), (
        "default --recent must be 12, not 3"
    )
    assert _count_lesson_lines(written_default) == 6


# --- Behavior 10 -- missing LEARNINGS.md is tolerated ----------------------
def test_b10_missing_learnings_tolerated(tmp_path, capsys):
    cfg = foundry.load_config(str(_write_cfg(tmp_path)))
    cfg_path = tmp_path / "config.json"
    assert not pathlib.Path(cfg.learnings).exists(), "learnings file must be absent"
    agents_md = pathlib.Path(cfg.repo) / "AGENTS.md"

    rc = foundry.main(["agents", "--config", str(cfg_path)])   # must not raise
    capsys.readouterr()
    assert rc == 0, "agents must return 0 when LEARNINGS.md is absent"
    assert agents_md.exists(), "agents must still write a valid AGENTS.md"
    # built from the empty-text placeholder digest
    assert agents_md.read_text() == foundry.render_agents_md("", cfg.name, recent=12)
    assert "## Recent lessons (last 0 of 0)" in agents_md.read_text()


# --- Behavior 11 -- repo-agnostic target; parent dir auto-created ----------
def test_b11_repo_agnostic_target(tmp_path, capsys):
    # cfg.repo points at a NESTED path whose parent does not exist yet, proving
    # the command computes the target from `repo` only and mkdirs parents.
    nested_repo = tmp_path / "does" / "not" / "exist" / "repo"
    assert not nested_repo.exists()
    text = _learnings_text(2, "pat")
    cfg = _cfg_with_learnings(tmp_path, text, repo=str(nested_repo))
    cfg_path = tmp_path / "config.json"

    rc = foundry.main(["agents", "--config", str(cfg_path)])
    capsys.readouterr()
    assert rc == 0
    target = pathlib.Path(cfg.repo) / "AGENTS.md"
    assert target.exists(), "agents did not create <cfg.repo>/AGENTS.md at the config-derived path"
    assert target == nested_repo / "AGENTS.md", "written path is not <cfg.repo>/AGENTS.md"


# ==========================================================================
# C. Non-regression (offline)
# ==========================================================================

# --- Behavior 12 -- imports + --help lists all subcommands + old ones work --
def test_b12_modules_import_and_helpers_callable():
    assert foundry is not None
    assert dispatcher is not None
    assert callable(foundry.render_agents_md)
    assert callable(foundry.learnings_digest)
    # pre-existing control-flow entry points untouched (still present + callable)
    for fn in ("build_prompt", "run_iteration", "run_continuous", "run_stage"):
        assert callable(getattr(foundry, fn)), f"foundry.{fn} missing/not callable (regression)"


def test_b12_help_lists_all_subcommands(capsys):
    with pytest.raises(SystemExit) as ei:
        foundry.main(["--help"])
    assert ei.value.code == 0
    out = capsys.readouterr().out
    for sub in ("run", "once", "doctor", "learnings", "agents"):
        assert sub in out, f"subcommand {sub!r} missing from --help output:\n{out}"


def test_b12_learnings_subcommand_still_works(tmp_path, capsys):
    text = _learnings_text(6, "regression pat")
    _cfg_with_learnings(tmp_path, text)
    cfg_path = tmp_path / "config.json"
    rc = foundry.main(["learnings", "--config", str(cfg_path)])
    out = capsys.readouterr().out
    assert rc == 0, "pre-existing `learnings` subcommand regressed"
    assert "## Patterns" in out
    assert "## Recent lessons (last 6 of 6)" in out
